### ISSUE TITLE
Music Speed?

### ISSUE THREAD

**Issue by GENERALWATERS** [Yoshify/DiscJockey#6]
After a certain amount of time, the boombox just slows all of the songs down and never speeds back up. Like every song played or new ones loaded are at like half play speed.

**Comment by Yoshify** [comment]
I believe this is fixed in 1.1.0 - could you please give it a go?

**Comment by GENERALWATERS** [comment]
So, I put the file in the Assests folder and all the .dll files in the Plugins folder, and now the mod doesn't work at all in game...

**Comment by GENERALWATERS** [comment]
I updated again and it's still not working.....any advice or help?

**Comment by Yoshify** [comment]
Could you please provide a screenshot of your `BepInEx/plugins/Yoshify-DiscJockey` folder? :)
